# Generated by Django 4.0 on 2021-12-27 21:20

from django.db import migrations, models
import django.db.models.deletion
import poison.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('key', models.CharField(default=poison.models.gen_key, max_length=16, primary_key=True, serialize=False)),
                ('center_deck', models.TextField(max_length=104)),
                ('left_deck', models.TextField(max_length=104)),
                ('right_deck', models.TextField(max_length=104)),
                ('turn', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('key', models.CharField(default=poison.models.gen_key, max_length=16, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='GamePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('cards', models.CharField(default='', max_length=104)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poison.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poison.player')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='GameAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('action', models.IntegerField(choices=[(1, 'Playerjoined'), (2, 'Playerleft'), (3, 'Cardplayed'), (4, 'Poisoncalled')])),
                ('data', models.CharField(max_length=256)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poison.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poison.gameplayer')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
    ]
