# Generated by Django 4.0 on 2021-12-27 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poison', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='gameplayer',
            index=models.Index(fields=['game', 'player'], name='poison_game_game_id_c0381f_idx'),
        ),
    ]
