# Generated by Django 4.0 on 2021-12-28 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poison', '0002_gameplayer_poison_game_game_id_c0381f_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameaction',
            options={'ordering': ['-index']},
        ),
        migrations.AlterField(
            model_name='gameaction',
            name='action',
            field=models.IntegerField(choices=[(1, 'Cardplayed'), (2, 'Carddrawn'), (3, 'Poisoncalled')]),
        ),
    ]
